fitgrid/epochs.py
fitgrid/tools.py
tests/test_tools.py

Duplicate indices message

---

fitgrid/epochs.py
fitgrid/fitgrid.py
requirements.txt

Trim requirements

---

.travis.yml

Expectation: new code is added through pull requests to dev.
Documentation is updated by pushing to docs.

Try to separate docs build.

---

README.md

Add link to docs and installation instructions to README.

---

docs/source/reference.rst
fitgrid/epochs.py
fitgrid/fitgrid.py
fitgrid/io.py

API reference

---

fitgrid/epochs.py
tests/test_epochs.py

Use EPOCH_ID and TIME as index internally in Epochs.table, test that.

---

fitgrid/epochs.py
fitgrid/fitgrid.py
tests/test_fitgrid.py

Epoch id addition

---

fitgrid/epochs.py
fitgrid/fake_data.py
fitgrid/fitgrid.py
fitgrid/io.py
tests/test_epochs.py
tests/test_fake_data.py
tests/test_fitgrid.py
tests/test_io.py

Make Epochs and FitGrid objects channel aware, refactor, add tests.

---

docs/source/reference.rst
fitgrid/epochs.py
fitgrid/fake_data.py

Arbitrary models

---

fitgrid/epochs.py

Add mixed models runner

---

fitgrid/epochs.py
tests/test_epochs.py

This method calculates epochs' Euclidean distances from the "mean epoch".

Add Epochs.distances.

---

fitgrid/epochs.py
fitgrid/fitgrid.py
tests/test_fitgrid.py

Make epoch_index and snapshots hidden attributes.

---

fitgrid/epochs.py

Use all channels by default in run_model.

---

fitgrid/fitgrid.py
tests/test_fitgrid.py

Fix single channel hiccup in plot_betas

---

fitgrid/fitgrid.py
tests/test_fitgrid.py

Deduplicate channels when slicing a FitGrid.

---

fitgrid/fitgrid.py
tests/test_fitgrid.py

Add option to plot single betas legend below all plots.

---

fitgrid/epochs.py
fitgrid/fitgrid.py
fitgrid/tools.py
tests/test_epochs.py
tests/test_fitgrid.py
tests/test_tools.py

Slicing duplicate channels

---

fitgrid/epochs.py
fitgrid/fitgrid.py
fitgrid/plots.py

Return fig/axes in plots and add colorbar to rsquared plot.

---

tests/test_epochs.py
tests/test_fitgrid.py

Speed up tests a bit by decreasing data sizes.

---

fitgrid/epochs.py
tests/test_epochs.py

Fix lmer channels

---

.travis.yml
environment.yml
meta.yaml
tests/environment.yml
tests/test_epochs.py

Conda travis

---

fitgrid/epochs.py
tests/test_epochs.py

Add more parameters to epochs.lmer that can be used by pymer4.

---

tests/test_epochs.py

Add lmer correctness tests, rename test_lm to test_lm_correctness etc.

---

fitgrid/epochs.py
tests/test_epochs.py

Set correct evaluation environment (eval_env=4) for patsy in lm.

---

fitgrid/epochs.py
fitgrid/tools.py
tests/test_tools.py

Design matrix check

---

fitgrid/fitgrid.py
tests/test_fitgrid.py

Make sure all attributes of a FitGrid object show up in __dir__

---

fitgrid/utils/__init__.py
fitgrid/utils/lm.py
tests/test_utils_lm.py

Add VIF calculator under fitgrid.utils.lm.get_vifs.

---

fitgrid/__init__.py
fitgrid/defaults.py
fitgrid/epochs.py
fitgrid/fake_data.py
fitgrid/fitgrid.py
fitgrid/io.py
fitgrid/models.py
fitgrid/utils/lmer.py
tests/test_epochs.py
tests/test_fake_data.py
tests/test_fitgrid.py
tests/test_io.py
tests/test_utils_lmer.py

Replace top-level constants with parameters, massive refactor.

---

conda/environment.yml

Update channel aportnoy -> kutaslab in environment.yml

---

fitgrid/fitgrid.py
tests/test_fitgrid.py

Still trying to figure out what `anova(m1, m2)` does exactly in R.

Add LMER model comparison based on AIC

---

conda/environment.yml
conda/meta.yaml

Pin NumPy at 1.15.4

---

conda/meta.yaml
fitgrid/__init__.py
fitgrid/utils/lm.py
fitgrid/utils/summary.py
tests/test_utils_lm.py
tests/test_utils_summary.py

tidied utils.lm statsmodels attributes
bug fix for AIC plotting, plus tweak so plots respect index and column label order in summary_df
temporary tqdm workaround in lm vif

Refresh tpu

---

.travis.yml
ci/conda_upload.sh
ci/ghpages_upload.sh
conda/meta.yaml
docs/source/conf.py
fitgrid/__init__.py

Patch to sync PyPI and Anaconda Cloud package distribution for vN.N.N releases

release 0.4.6

---

conda/meta.yaml

rpy2 3.4.3 is incompatible w/ pymer4, cause TBD

actions failing, testing rpy !=3.4.3

---

.github/workflows/fitgrid-cid.yml
conda/meta.yaml

add linux selector for build compilers in meta.yaml

---

conda/meta.yaml
docs/source/conf.py
fitgrid/__init__.py
setup.py

No functional changes
* add conda/meta.yaml pin pymer4 >=0.7.2 to handle rpy2 breaking change
* fix author names

minor CI update, corrections

---

joss/paper.md

Hi @andportnoy @turbach I am going to review your submission of `fitgrid` to JOSS. I'll link each issue and PR that I open back to the review thread https://github.com/openjournals/joss-reviews/issues/3293 so that we can have an overview of my requests / questions / hints / ... and check back later in how far they have been addressed or should be dropped.
In this first PR I make some stylistic suggestions (mostly some fixes) after reading the paper.
I'll also try to make some comments in the diff where I think you should clarify the paper. GitHub sometimes only allows inline comments close to lines that have been "touched", so I may simply make another post below this one, if I cannot accommodate a comment in inline text.

[JOSS] doc: minor language edits of the paper
